# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '07:00'
    target-branch: 'develop'
    labels:
      - 'merge'
      - 'dependencies'
    commit-message:
      prefix: 'feat'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
