# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
    target-branch: 'develop'
    labels:
      - 'merge'
      - 'dependencies'
    commit-message:
      prefix: 'feat'
      include: 'scope'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 1

  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    labels:
      - 'merge'
      - 'dependencies'
    commit-message:
      prefix: 'feat'
      include: 'scope'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 1
