name: better_informed_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version handled in CD workflows - check out .github/workflows/cd_prod.yml and .github/workflows/cd_staging.yml
version: 1.12.0+0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: 3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: 4.0.1
  freezed_annotation: 2.0.3
  fimber: 0.6.6
  injectable: 1.5.3
  get_it: 7.2.0
  json_annotation: 4.5.0
  bloc: 8.0.3
  flutter_hooks: 0.18.4
  easy_localization: 3.0.1
  clock: 1.1.0
  url_launcher: 6.1.2
  path: 1.8.1
  path_provider: 2.0.10
  flutter_svg: 1.0.3
  graphql_flutter: 5.1.0
  fresh_graphql: 0.5.2
  modal_bottom_sheet: 2.0.1
  uni_links: 0.5.1
  flutter_secure_storage: 5.0.2
  firebase_core: 1.17.0
  firebase_messaging: 11.4.0
  firebase_auth: 3.3.18
  sign_in_with_apple: 3.3.0
  google_sign_in: 5.3.1
  flutter_keyboard_visibility: 5.2.0
  email_validator: 2.0.1
  flutter_markdown:
    git:
      url: https://github.com/dawidkiteo/packages.git
      ref: version/0-6-8
      path: packages/flutter_markdown
  cloudinary_sdk: 3.0.1+7
  rxdart: 0.27.3
  hive: 2.2.1
  hive_flutter: 1.1.0
  package_info_plus: 1.4.2
  sentry_flutter: 6.5.1
  shimmer: 2.0.0
  jiffy: 5.0.0
  flutter_html: 2.2.1
  flutter_segment: 3.3.0
  fluttertoast: 8.0.9
  flutter_email_sender: 5.1.0
  share_plus: 4.0.4
  visibility_detector: 0.3.3
  expand_tap_area: 1.1.0
  flutter_styled_toast: 2.1.3
  tutorial_coach_mark: 1.2.2
  golden_toolkit: 0.13.0
  auto_size_text: 3.0.0
  flutter_custom_tabs: 1.0.4
  flutter_inappwebview: 5.4.3+7
  cached_network_image: 3.2.1
  social_share: 2.2.1
  scrolls_to_top: 1.1.1
  dotted_border: 2.0.0+2
  audio_video_progress_bar: 0.10.0
  upgrader: 4.1.2
  just_audio: 0.9.21
  audio_service: 0.18.4
  audio_session: 0.1.6+1
  launchdarkly_flutter_client_sdk: 1.0.0
  jwt_decoder: 2.0.1
  appsflyer_sdk: 6.5.2+2
  app_tracking_transparency: 2.0.2+4
  flutter_staggered_grid_view: 0.6.1
  sliver_tools: 0.2.6
  gql: 0.13.1
  http: 0.13.4
  provider: 6.0.2
  markdown: 4.0.1
  html: 0.15.0
  shared_preferences: 2.0.15
  oauth2: 2.0.0
  flutter_web_auth: 0.4.1
  chewie: 1.3.3
  video_player: 2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 4.0.0
  build_runner: 2.1.11
  freezed: 2.0.3+1
  injectable_generator: 1.5.3
  json_serializable: 6.2.0
  mockito: 5.2.0
  bloc_test: 9.0.3
  hive_generator: 1.1.3
  flutter_launcher_icons: 0.9.2
  flutter_lints: 2.0.1

dependency_overrides:
  flutter_svg: 1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-VariableFont_wght.ttf
        - asset: fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/vector_graphics/
    - assets/raster_graphics/
