name: better_informed_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version handled in CD workflows - check out .github/workflows/cd_prod.yml and .github/workflows/cd_staging.yml
version: 1.63.0+0

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: 3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: 5.0.2
  freezed_annotation: 2.2.0
  fimber: 0.6.6
  injectable: 2.1.0
  get_it: 7.2.0
  json_annotation: 4.8.0
  bloc: 8.1.0
  flutter_hooks: 0.18.5+1
  clock: 1.1.1
  url_launcher: 6.1.8
  path: 1.8.2
  path_provider: 2.0.12
  flutter_svg: 1.1.6
  graphql_flutter: 5.1.1
  fresh_graphql: 0.5.2
  modal_bottom_sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet.git
      ref: 42da8b016ca254c1a4fa01be2edbef2cadd71bd2
      path: modal_bottom_sheet
  uni_links: 0.5.1
  flutter_secure_storage: 7.0.1
  firebase_core: 2.4.1
  firebase_messaging: 14.2.1
  sign_in_with_apple: 4.3.0
  google_sign_in: 5.4.3
  flutter_keyboard_visibility: 5.4.0
  email_validator: 2.1.17
  flutter_markdown:
    git:
      url: https://github.com/dawidkiteo/packages.git
      ref: version/0-7-2
      path: packages/flutter_markdown
  cloudinary_sdk: 4.0.2+10
  rxdart: 0.27.7
  hive: 2.2.3
  hive_flutter: 1.1.0
  package_info_plus: 3.0.2
  sentry_flutter: 6.19.0
  shimmer: 2.0.0
  jiffy: 5.0.0
  flutter_segment: 3.13.0
  fluttertoast: 8.1.2
  flutter_email_sender: 5.2.0
  share_plus: 6.3.0
  visibility_detector: 0.3.3
  flutter_styled_toast: 2.1.3
  tutorial_coach_mark: 1.2.4
  golden_toolkit: 0.14.0
  auto_size_text: 3.0.0
  flutter_custom_tabs: 1.0.4
  flutter_inappwebview: 5.7.2+3
  cached_network_image:
    git:
      url: https://github.com/davidmartos96/flutter_cached_network_image.git
      ref: ce6d67111c727c3a44849d67d1c730985d999c9e
      path: cached_network_image
  social_share: 2.3.1
  scrolls_to_top: 2.0.0
  dotted_border: 2.0.0+3
  audio_video_progress_bar: 0.11.0
  upgrader: 6.0.1
  just_audio: 0.9.31
  audio_service: 0.18.9
  audio_session: 0.1.13
  launchdarkly_flutter_client_sdk: 1.2.0
  jwt_decoder: 2.0.1
  appsflyer_sdk:
    git:
      url: https://github.com/minoesteban/appsflyer-flutter-plugin
      ref: bd2736e033930a4848220742f8120c276d6eab29
  app_tracking_transparency: 2.0.3
  flutter_staggered_grid_view: 0.6.2
  sliver_tools: 0.2.8
  gql: 0.14.1-alpha+1672756470474
  http: 0.13.5
  provider: 6.0.5
  markdown: 6.0.1
  html: 0.15.1
  shared_preferences: 2.0.17
  oauth2: 2.0.1
  flutter_web_auth: 0.5.0
  chewie: 1.4.0
  video_player: 2.5.1
  connectivity_plus: 3.0.2
  gql_build: 0.7.0
  neat_periodic_task: 2.0.0
  responsive_framework: 0.2.0
  purchases_flutter: 4.8.0
  dotted_line: 3.1.0
  collection: 1.17.0
  dart_code_metrics: 5.5.0
  facebook_app_events: 0.18.3
  retry: 3.1.0
  platform: 3.1.0
  app_settings: 4.2.0
  adaptive_theme: 3.1.1
  flutter_app_badger: 1.5.0
  phrase: 1.0.1
  intl: 0.17.0
  flutter_cache_manager: 3.3.0
  smooth_page_indicator: 1.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  auto_route_generator: 5.0.3
  build_runner: 2.3.3
  freezed: 2.3.2
  injectable_generator: 2.1.3
  json_serializable: 6.6.0
  mockito: 5.3.2
  bloc_test: 9.1.0
  hive_generator: 2.0.0
  flutter_launcher_icons: 0.11.0
  flutter_lints: 2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  fonts:
    - family: Lausanne
      fonts:
        - asset: fonts/TWKLausanne-400.ttf
          weight: 400
        - asset: fonts/TWKLausanne-550.ttf
          weight: 500
    - family: IvarText
      fonts:
        - asset: fonts/IvarText-Regular.ttf
          weight: 400
        - asset: fonts/IvarText-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/IvarText-SemiBold.ttf
          weight: 600
        - asset: fonts/IvarText-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: IvarHeadline
      fonts:
        - asset: fonts/IvarHeadline-SemiBold.ttf
          weight: 600
        - asset: fonts/IvarHeadline-SemiBoldItalic.ttf
          weight: 600
          style: italic

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vector_graphics/
    - assets/raster_graphics/
    - assets/raster_graphics/placeholders/
