name: better_informed_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version handled in CD workflows - check out .github/workflows/cd_prod.yml and .github/workflows/cd_staging.yml
version: 1.28.0+0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: 4.2.1
  freezed_annotation: 2.1.0
  fimber: 0.6.6
  injectable: 1.5.3
  get_it: 7.2.0
  json_annotation: 4.6.0
  bloc: 8.1.0
  flutter_hooks: 0.18.5+1
  easy_localization: 3.0.1
  clock: 1.1.0
  url_launcher: 6.1.5
  path: 1.8.1
  path_provider: 2.0.11
  flutter_svg: 1.1.4
  graphql_flutter: 5.1.0
  fresh_graphql: 0.5.2
  modal_bottom_sheet: 2.1.0
  uni_links: 0.5.1
  flutter_secure_storage: 5.1.2
  firebase_core: 1.21.0
  firebase_messaging: 12.0.3
  firebase_auth: 3.6.4
  sign_in_with_apple: 4.1.0
  google_sign_in: 5.4.1
  flutter_keyboard_visibility: 5.3.0
  email_validator: 2.1.17
  flutter_markdown:
    git:
      url: https://github.com/dawidkiteo/packages.git
      ref: version/0-7-0
      path: packages/flutter_markdown
  cloudinary_sdk: 4.0.2+10
  rxdart: 0.27.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  package_info_plus: 1.4.3+1
  sentry_flutter: 6.9.1
  shimmer: 2.0.0
  jiffy: 5.0.0
  flutter_html: 2.2.1
  flutter_segment: 3.11.0
  fluttertoast: 8.0.9
  flutter_email_sender: 5.1.0
  share_plus: 4.0.10+1
  visibility_detector: 0.3.3
  flutter_styled_toast: 2.1.3
  tutorial_coach_mark: 1.2.4
  golden_toolkit: 0.13.0
  auto_size_text: 3.0.0
  flutter_custom_tabs: 1.0.4
  flutter_inappwebview:
    git:
      url: https://github.com/MohammedXAbdo/flutter_inappwebview.git
      ref: 93801e0ab78e2e017df2f136e24a59eacf6266e2
  cached_network_image: 3.2.1
  social_share: 2.2.1
  scrolls_to_top: 1.1.1
  dotted_border: 2.0.0+2
  audio_video_progress_bar: 0.10.0
  upgrader: 4.6.0
  just_audio: 0.9.28
  audio_service: 0.18.7
  audio_session: 0.1.10
  launchdarkly_flutter_client_sdk: 1.1.4
  jwt_decoder: 2.0.1
  appsflyer_sdk: 6.5.2+2
  app_tracking_transparency: 2.0.2+4
  flutter_staggered_grid_view: 0.6.2
  sliver_tools: 0.2.7
  gql: 0.13.1
  http: 0.13.5
  provider: 6.0.3
  markdown: 5.0.0
  html: 0.15.0
  shared_preferences: 2.0.15
  oauth2: 2.0.0
  # https://github.com/LinusU/flutter_web_auth/pull/118
  flutter_web_auth:
    git:
      url: https://github.com/noga-dev/flutter_web_auth.git
  chewie: 1.3.4
  video_player: 2.4.7
  connectivity_plus: 2.3.6+1
  gql_build:
    git:
      url: https://github.com/gql-dart/gql.git
      path: codegen/gql_build
      ref: c6644dab44234468bfe134cf6316a965912a2bce
  neat_periodic_task: 2.0.0
  responsive_framework: 0.2.0
  purchases_flutter: 4.2.1
  dotted_line: 3.1.0
  collection: 1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 4.2.0
  build_runner: 2.2.0
  freezed: 2.0.3+1
  injectable_generator: 1.5.3
  json_serializable: 6.3.1
  mockito: 5.2.0
  bloc_test: 9.1.0
  hive_generator: 1.1.3
  flutter_launcher_icons: 0.10.0
  flutter_lints: 2.0.1
  dart_code_metrics: 4.16.0

dependency_overrides:
  flutter_svg: 1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-VariableFont_wght.ttf
        - asset: fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/vector_graphics/
    - assets/raster_graphics/
    - assets/raster_graphics/placeholders/
