name: better_informed_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+0

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: 2.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: 3.2.2
  freezed_annotation: 1.1.0
  fimber: 0.6.5
  injectable: 1.5.3
  get_it: 7.2.0
  json_annotation: 4.4.0
  bloc: 8.0.2
  flutter_hooks: 0.18.2+1
  easy_localization: 3.0.0
  clock: 1.1.0
  url_launcher: 6.0.20
  path: 1.8.0
  path_provider: 2.0.9
  flutter_svg: 1.0.3
  graphql_flutter: 5.0.1
  fresh_graphql: 0.5.1
  modal_bottom_sheet: 2.0.0
  uni_links: 0.5.1
  flutter_secure_storage: 5.0.2
  firebase_core: 1.12.0
  firebase_messaging: 11.2.6
  firebase_auth: 3.3.7
  sign_in_with_apple: 3.3.0
  google_sign_in: 5.2.3
  flutter_keyboard_visibility: 5.1.1
  email_validator: 2.0.1
  flutter_markdown:
    git:
      url: https://github.com/dawidkiteo/packages.git
      ref: version/0-6-8
      path: packages/flutter_markdown
  cloudinary_sdk: 3.0.1+7
  rxdart: 0.27.3
  hive: 2.0.5
  hive_flutter: 1.1.0
  package_info_plus: 1.3.0
  sentry_flutter: 6.3.0
  shimmer: 2.0.0
  progressive_image: 2.0.0
  jiffy: 5.0.0
  flutter_html: 2.2.1
  flutter_segment: 3.3.0
  fluttertoast: 8.0.8
  flutter_email_sender: 5.1.0
  share_plus: 3.0.4
  visibility_detector: 0.2.2
  expand_tap_area: 1.1.0
  flutter_styled_toast: 2.0.0
  tutorial_coach_mark: 1.2.1
  golden_toolkit: 0.13.0
  auto_size_text: 3.0.0
  flutter_custom_tabs: 1.0.4
  flutter_inappwebview: 5.3.2
  cached_network_image: 3.2.0
  social_share: 2.2.1
  scrolls_to_top: 1.1.1
  dotted_border: 2.0.0+2
  audio_video_progress_bar: 0.10.0
  upgrader: 3.13.0
  just_audio: 0.9.20
  audio_service: 0.18.4
  audio_session: 0.1.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 3.2.1
  build_runner: 2.1.7
  freezed: 1.1.0
  injectable_generator: 1.5.2
  json_serializable: 6.1.4
  pedantic: 1.11.1
  mockito: 5.1.0
  bloc_test: 9.0.2
  hive_generator: 1.1.2
  flutter_launcher_icons: 0.9.2

dependency_overrides:
  flutter_svg: 1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-VariableFont_wght.ttf
        - asset: fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/vector_graphics/
    - assets/raster_graphics/
