import 'package:better_informed_mobile/data/article/database/entity/article_audio_file_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_content_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_content_type_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_header_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_image_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_kind_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_progress_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_progress_state_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/article_type_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/category_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/curation_info_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/curator_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/image_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/publisher_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/synchronizable_article_entity.hv.dart';
import 'package:better_informed_mobile/data/article/database/entity/synchronizable_article_progress_entity.hv.dart';
import 'package:better_informed_mobile/data/bookmark/database/entity/bookmark_data_entity.hv.dart';
import 'package:better_informed_mobile/data/bookmark/database/entity/bookmark_entity.hv.dart';
import 'package:better_informed_mobile/data/bookmark/database/entity/synchronizable_bookmark_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_calendar_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_entry_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_entry_item_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_entry_seen_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_entry_style_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_entry_style_type_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_introduction_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_section_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/brief_subsection_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/call_to_action_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/headline_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/relax_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/synchronizable_brief_entity.hv.dart';
import 'package:better_informed_mobile/data/daily_brief/database/entity/synchronizable_brief_entry_seen_entity.hv.dart';
import 'package:better_informed_mobile/data/subscription/database/entity/active_subscription_entity.hv.dart';
import 'package:better_informed_mobile/data/subscription/database/entity/subscription_origin_entity.hv.dart';
import 'package:better_informed_mobile/data/subscription/database/entity/subscription_plan_entity.hv.dart';
import 'package:better_informed_mobile/data/subscription/database/entity/subscription_plan_type_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/entry_style_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/entry_style_type_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/media_item_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/synchronizable_topic_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/topic_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/topic_entry_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/topic_preview_entity.hv.dart';
import 'package:better_informed_mobile/data/topic/database/entity/topic_publisher_information_entity.hv.dart';
import 'package:better_informed_mobile/data/user/database/entity/user_entity.hv.dart';
import 'package:hive_flutter/adapters.dart';

Future<void> initializeHive() async {
  await Hive.initFlutter();

  Hive.registerAdapter(ArticleHeaderEntityAdapter());
  Hive.registerAdapter(ArticleImageEntityAdapter());
  Hive.registerAdapter(ArticleKindEntityAdapter());
  Hive.registerAdapter(ArticleProgressEntityAdapter());
  Hive.registerAdapter(ArticleProgressStateEntityAdapter());
  Hive.registerAdapter(ArticleTypeEntityAdapter());
  Hive.registerAdapter(CategoryEntityAdapter());
  Hive.registerAdapter(CurationInfoEntityAdapter());
  Hive.registerAdapter(PublisherEntityAdapter());
  Hive.registerAdapter(CuratorEntityAdapter());
  Hive.registerAdapter(CuratorExpertEntityAdapter());
  Hive.registerAdapter(CuratorEditorEntityAdapter());
  Hive.registerAdapter(CuratorEditorialTeamEntityAdapter());
  Hive.registerAdapter(CuratorUnknownEntityAdapter());
  Hive.registerAdapter(ImageEntityAdapter());
  Hive.registerAdapter(ArticleCloudinaryImageEntityAdapter());
  Hive.registerAdapter(ArticleRemoteImageEntityAdapter());
  Hive.registerAdapter(ArticleUnknownImageEntityAdapter());
  Hive.registerAdapter(ArticleContentEntityAdapter());
  Hive.registerAdapter(ArticleContentTypeEntityAdapter());
  Hive.registerAdapter(ArticleEntityAdapter());
  Hive.registerAdapter(ArticleAudioFileEntityAdapter());
  Hive.registerAdapter(BookmarkEntityAdapter());
  Hive.registerAdapter(BookmarkDataEntityAdapter());
  Hive.registerAdapter(EntryStyleEntityAdapter());
  Hive.registerAdapter(EntryStyleTypeEntityAdapter());
  Hive.registerAdapter(MediaItemEntityAdapter());
  Hive.registerAdapter(TopicEntityAdapter());
  Hive.registerAdapter(TopicEntryEntityAdapter());
  Hive.registerAdapter(TopicPublisherInformationEntityAdapter());
  Hive.registerAdapter(SynchronizableArticleEntityAdapter());
  Hive.registerAdapter(SynchronizableTopicEntityAdapter());
  Hive.registerAdapter(UserEntityAdapter());
  Hive.registerAdapter(ActiveSubscriptionEntityAdapter());
  Hive.registerAdapter(ActiveSubscriptionFreeEntityAdapter());
  Hive.registerAdapter(ActiveSubscriptionTrialEntityAdapter());
  Hive.registerAdapter(ActiveSubscriptionPremiumEntityAdapter());
  Hive.registerAdapter(ActiveSubscriptionManualPremiumEntityAdapter());
  Hive.registerAdapter(SubscriptionPlanEntityAdapter());
  Hive.registerAdapter(SubscriptionPlanTypeEntityAdapter());
  Hive.registerAdapter(SynchronizableBookmarkEntityAdapter());
  Hive.registerAdapter(SynchronizableArticleProgressEntityAdapter());
  Hive.registerAdapter(BriefEntityAdapter());
  Hive.registerAdapter(HeadlineEntityAdapter());
  Hive.registerAdapter(BriefIntroductionEntityAdapter());
  Hive.registerAdapter(RelaxEntityAdapter());
  Hive.registerAdapter(CallToActionEntityAdapter());
  Hive.registerAdapter(BriefSectionEntityAdapter());
  Hive.registerAdapter(BriefSectionEntriesEntityAdapter());
  Hive.registerAdapter(BriefSectionSubsectionEntityAdapter());
  Hive.registerAdapter(BriefSectionUnknownEntityAdapter());
  Hive.registerAdapter(BriefEntryEntityAdapter());
  Hive.registerAdapter(BriefEntryItemEntityAdapter());
  Hive.registerAdapter(BriefEntryItemArticleEntityAdapter());
  Hive.registerAdapter(BriefEntryItemTopicEntityAdapter());
  Hive.registerAdapter(BriefEntryItemUnknownEntityAdapter());
  Hive.registerAdapter(BriefEntryStyleEntityAdapter());
  Hive.registerAdapter(BriefEntryStyleTypeEntityAdapter());
  Hive.registerAdapter(BriefSubsectionEntityAdapter());
  Hive.registerAdapter(TopicPreviewEntityAdapter());
  Hive.registerAdapter(SynchronizableBriefEntityAdapter());
  Hive.registerAdapter(BriefCalendarEntityAdapter());
  Hive.registerAdapter(SubscriptionOriginEntityAdapter());
  Hive.registerAdapter(BriefEntrySeenEntityAdapter());
  Hive.registerAdapter(SynchronizableBriefEntrySeenEntityAdapter());
}
