source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-flutter_version", "~> 1.1.13"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
