# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Submit to internal track in Google Play Store"
    lane :internal_play_store do
      upload_to_play_store(
        track: 'internal',
        json_key: "../google_play_credentials.json",
        version_code: flutter_version()["version_code"],
        aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
        skip_upload_screenshots: true,
        skip_upload_images: true,
        release_status: 'draft'
      )
    end

    desc "Submit to internal track in Google Play Store - staging"
    lane :internal_play_store_staging do
      upload_to_play_store(
        track: 'beta',
        package_name: 'so.informed.staging',
        json_key: "../google_play_credentials.json",
        version_code: flutter_version()["version_code"],
        aab: '../build/app/outputs/bundle/stageRelease/app-stage-release.aab',
        skip_upload_screenshots: true,
        skip_upload_images: true,
        release_status: 'draft'
      )
    end

    desc "Submit to staging firebase app distribution"
    lane :firebase_deploy do
        firebase_app_distribution(
            service_credentials_file: "../firebase_credentials.json",
            app: ENV["FIREBASE_APP_ID_ANDROID"],
            groups: "iteo, informed, external",
            apk_path: "../build/app/outputs/flutter-apk/app-stage-release.apk"
        )
    end
end
