name: CI Build

on:
  pull_request:
    branches: [main, develop]

env:
  JAVA_VERSION: '12.x'

jobs:
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      app: ${{ steps.filter.outputs.app }}
      android: ${{ steps.filter.outputs.android }}
      ios: ${{ steps.filter.outputs.ios }}
      tests: ${{ steps.filter.outputs.tests }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: 'json'
          filters: |
            app:
              - 'assets/**'
              - 'fonts/**'
              - 'lib/**'
              - '**.yaml'
            ios:
              - 'ios/**'
            android:
              - 'android/**'
            tests:
              - 'test/**'
  set_slack_id:
    name: Set slack id
    runs-on: ubuntu-latest
    outputs:
      slack_id: ${{env.slack_id}}
    steps:
      - name: Set slack Lukasz id
        if: github.event.pull_request.user.login == 'LukaszWojcikIteo'
        run: |
          echo "slack_id=U02B9DG36RZ" >> $GITHUB_ENV
      - name: Set slack Estaban id
        if: github.event.pull_request.user.login == 'minoesteban'
        run: |
          echo "slack_id=U02KFBZ3N7P" >> $GITHUB_ENV
      - name: Set slack Jan id
        if: github.event.pull_request.user.login == 'jlukas99'
        run: |
          echo "slack_id=U03F4JSQCGP" >> $GITHUB_ENV
      - name: Set Filipe slack id
        if: github.event.pull_request.user.login == 'filipepatricio'
        run: |
          echo "slack_id=U02J1L1AX4J" >> $GITHUB_ENV

  commit_lint:
    name: Commit linting
    needs: [set_slack_id]
    runs-on: ubuntu-latest
    outputs:
      succeeded: ${{ steps.result.outputs.result }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5

      - name: Slack message commit linting failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':x:'
          job_name: Commit linting
          status: ${{ job.status }}
          fields: repo,author,job,took,workflow,pullRequest
          mention: ${{needs.set_slack_id.outputs.slack_id}}
          if_mention: 'failure'
          channel: 'C03HLNW54EN'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASES_CHANNEL_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Result
        id: result
        if: success()
        run: echo "::set-output name=result::true"

  # //TODO: Uncomment when dart-code-metrics-action upgrades flutter to 3.7.0
  # dart_code_metrics:
  #   name: Dart code metrics
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel previous runs
  #       uses: styfle/cancel-workflow-action@0.11.0
  #       with:
  #         access_token: ${{ github.token }}
  #     - uses: actions/checkout@v3
  #     - uses: dart-code-checker/dart-code-metrics-action@v3
  #       with:
  #         github_token: ${{ github.token }}
  #         pull_request_comment: true
  #         fatal_warnings: true

  code_lint_test:
    needs: [set_slack_id, changes, commit_lint]
    if: ${{ needs.changes.outputs.tests == 'true' || needs.changes.outputs.app == 'true' || needs.changes.outputs.android == 'true' || needs.changes.outputs.ios == 'true' }}
    name: Linting & Testing
    runs-on: ubuntu-latest
    outputs:
      succeeded: ${{ steps.result.outputs.result }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      # Your pubspec.yaml file must contain the Flutter version under the environment:flutter: key.
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true
      - run: |
          flutter format -l 120 --dry-run --set-exit-if-changed .

      - name: Build
        run: |
          flutter pub get
          flutter pub run easy_localization:generate --source-dir ./assets/translations -f keys -o local_keys.g.dart
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze & Test
        run: |
          flutter analyze --no-pub
          flutter test test/unit/wrapper_test.dart

      - name: Slack message code linting & Testing failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':x:'
          job_name: Linting & Testing
          status: ${{ job.status }}
          fields: repo,author,job,took,workflow,pullRequest
          mention: ${{needs.set_slack_id.outputs.slack_id}}
          if_mention: 'failure'
          channel: 'C03HLNW54EN'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASES_CHANNEL_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Result
        id: result
        if: success()
        run: echo "::set-output name=result::true"

  build_android:
    needs: [set_slack_id, changes, commit_lint, code_lint_test]
    if: ${{ needs.changes.outputs.app == 'true' || needs.changes.outputs.android == 'true' }}
    name: Android build
    runs-on: ubuntu-latest
    outputs:
      succeeded: ${{ steps.result.outputs.result }}
    timeout-minutes: 20
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      # Your pubspec.yaml file must contain the Flutter version under the environment:flutter: key.
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - name: Setup
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true

      - name: Clean & Build
        run: |
          flutter pub get
          flutter pub run easy_localization:generate --source-dir ./assets/translations -f keys -o local_keys.g.dart
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android app
        run: flutter build apk --release --dart-define=env=prod --flavor prod

      - name: Slack message android app building failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':x:'
          job_name: Android build
          status: ${{ job.status }}
          fields: repo,author,job,took,workflow,pullRequest
          mention: ${{needs.set_slack_id.outputs.slack_id}}
          if_mention: 'failure'
          channel: 'C03HLNW54EN'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASES_CHANNEL_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Result
        id: result
        if: success()
        run: echo "::set-output name=result::true"

  build_ios:
    needs: [set_slack_id, changes, commit_lint, code_lint_test]
    if: ${{ needs.changes.outputs.app == 'true' || needs.changes.outputs.ios == 'true' }}
    name: iOS build
    runs-on: macos-12
    outputs:
      succeeded: ${{ steps.result.outputs.result }}
    timeout-minutes: 25
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout code
        uses: actions/checkout@v3

      # Your pubspec.yaml file must contain the Flutter version under the environment:flutter: key.
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - name: Setup
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          # cache: true

      - name: Clean & Build
        run: |
          flutter pub get
          flutter pub run easy_localization:generate --source-dir ./assets/translations -f keys -o local_keys.g.dart
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS app
        run: flutter build ios --release --no-codesign --dart-define=env=prod --flavor prod --bundle-sksl-path warmup.sksl.json

      - name: Slack message iOS app building failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':x:'
          job_name: iOS build
          status: ${{ job.status }}
          fields: repo,author,job,took,workflow,pullRequest
          mention: ${{needs.set_slack_id.outputs.slack_id}}
          if_mention: 'failure'
          channel: 'C03HLNW54EN'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASES_CHANNEL_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Result
        id: result
        if: success()
        run: echo "::set-output name=result::true"

  all_jobs_succeeded:
    needs: [changes, commit_lint, code_lint_test, build_android, build_ios]
    name: All jobs succeeded
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Commit linting failed
        if: ${{ needs.commit_lint.outputs.succeeded != 'true' }}
        run: exit 1

      - name: Code linting & Testing failed
        if: ${{ (needs.changes.outputs.tests == 'true' || needs.changes.outputs.app == 'true' || needs.changes.outputs.android == 'true' || needs.changes.outputs.ios == 'true') && needs.code_lint_test.outputs.succeeded != 'true' }}
        run: exit 1

      - name: Android app building failed
        if: ${{ (needs.changes.outputs.app == 'true' || needs.changes.outputs.android == 'true') &&  needs.build_android.outputs.succeeded != 'true' }}
        run: exit 1

      - name: iOS app building failed
        if: ${{ (needs.changes.outputs.app == 'true' || needs.changes.outputs.ios == 'true') && needs.build_ios.outputs.succeeded != 'true' }}
        run: exit 1
