name: CI

on:
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**/README.md'

env:
  JAVA_VERSION: '12.x'

jobs:
  commit_lint:
    name: Commit linting
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v4

  code_lint:
    name: Code linting
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      # Your pubspec.yaml file must contain the Flutter version under the environment:flutter: key.
      - name: Get Flutter version from Pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
      - run: flutter format -l 120 --set-exit-if-changed .

  app_ci_and_android_build:
    name: App CI and Android build test
    needs: [commit_lint, code_lint]
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      # Your pubspec.yaml file must contain the Flutter version under the environment:flutter: key.
      - name: Get Flutter version from Pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1

      - name: Sets up a flutter environment for use in actions
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
      - run: echo "Setup flutter environment with version ${{ steps.get-flutter-version.outputs.version }}"

      - name: Run flutter clean
        run: flutter clean

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Run easy_localization:generate and generate files
        run: flutter pub run easy_localization:generate --source-dir ./assets/translations -f keys -o local_keys.g.dart

      - name: Run build_runner and generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Statically analyze the Dart code for any errors
        run: flutter analyze .

      - name: Run tests
        run: flutter test -x visual

      - name: Build Android app release for prod
        run: flutter build apk --release --dart-define=env=prod --flavor prod

  build_ios_app:
    name: Test building iOS app
    needs: [app_ci_and_android_build]
    runs-on: macos-latest
    timeout-minutes: 25
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      # Your pubspec.yaml file must contain the Flutter version under the environment:flutter: key.
      - name: Get Flutter version from Pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1

      - name: Sets up a flutter environment for use in actions
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
      - run: echo "Setup flutter environment with version ${{ steps.get-flutter-version.outputs.version }}"

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Run easy_localization:generate and generate files
        run: flutter pub run easy_localization:generate --source-dir ./assets/translations -f keys -o local_keys.g.dart

      - name: Run build_runner and generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS app release for prod
        run: flutter build ios --release --no-codesign --dart-define=env=prod --flavor prod
