name: Scheduled release

on:
  workflow_dispatch:
  schedule:
    # Always set hour in UTC timezone
    - cron: '0 13 * * FRI'

jobs:
  promote-dev-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ github.token }}
          source_branch: 'develop'
          destination_branch: 'main'
          pr_title: 'Scheduled release'
          pr_label: 'merge'
