name: Scheduled release

on:
  workflow_dispatch:
  schedule:
    # This is set in UTC timezone, so we set 13 to run at 14 in UTC+1
    - cron: '0 13 * * FRI'

jobs:
  promote-dev-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'develop'
          destination_branch: 'main'
          pr_title: 'Scheduled release'
