name: UI changes

# There is no merged event, so we have to listen for pull request closed
# and than add to our job condition "if: github.event.pull_request.merged == true"

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '**.yaml'
      - 'analysis_options.yaml'
      - 'commitlint.config.js'
      - '**/README.md'
      - 'scripts/**'
      - '.vscode/**'
      - '.github/**'
      - '.idea/**'
      - '.fvm/**'
      - '.dart_tool/**'

jobs:
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      app: ${{ steps.filter.outputs.app }}
      tests: ${{ steps.filter.outputs.tests }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: 'json'
          filters: |
            app:
              - 'assets/**'
              - 'fonts/**'
              - 'lib/**'
            tests:
              - 'test/visual/**'

  ui-changes:
    needs: [changes]
    if: ${{ needs.changes.outputs.tests == 'true' || needs.changes.outputs.app == 'true' }}
    name: UI changes
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # ... because we want to be able to reset to the merge-base

      # Your pubspec.yaml file must contain the Flutter version under the environment:flutter: key.
      - name: Get Flutter version from pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}

      - name: Get glutter dependencies for base branch
        run: flutter pub get

      - name: Generate ui changes report
        run: make ui_changes_report

      - name: Upload ui changes report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ui_changes_report
          path: test/visual/ui_changes/
          if-no-files-found: ignore
          retention-days: 3
